### ISSUE TITLE
Can't use a parameter in a module value

### ISSUE THREAD

**Issue by gionn** [NomicFoundation/hardhat-ignition#663]
Defined a parameter in parameters.json:

```
{
  "MyModule": {
    "valueGwei": 1000000000
  }
}
```

and then trying to use it in a module:

```
  const deployer = m.contract("Deployer", [], {
    value: m.getParameter("valueGwei"),
  });
```

while deploying I get:

```
[ MyModule ] validation failed ⛔

The module contains futures that would fail to execute:

MyModule#Deployer:
 - IGN726: Module parameter 'valueGwei' must be of type 'bigint' but is 'number'

Update the invalid futures and rerun the deployment.
```

**Comment by kanej** [comment]
Hey @gionn, that is an issue.

I am unsure how we should resolve it though.

Clearly we need a way to represent a bigint in the parameters json file. Maybe it would be enough to enhance our parameter json file serialization/deserialization to treat bigint's as strings of the format: `/\d+n/`.

**Comment by gionn** [comment]
The first thing that I tried after seeing the error was to try to define it as "1000000000n", so it could be enough.

I wonder if you can have a custom deserializer controlled by a `getParameter` optional argument to convert/cast from number to bigint.

**Comment by kanej** [comment]
We have worked through our design process. Our intention is to approach this in two steps:
1. Enhance our JSON deserializer with a *reviver* function that detects the regex pattern /\d+n/ in strings then converts them to BigInt.
2. Investigate leveraging module parameters from within `hardhat.config.{js,ts}`, captured as issue https://github.com/NomicFoundation/hardhat-ignition/issues/691

Step one will be implemented and release to support users now in using BigInts. As it affects only plugin deserialization and not the public programmatic api more generally we are happy this tradeoff. The investigation task is a follow up to assess our options for arresting a slow descent into defining our own intricate serialization/deserialization mechanism.

**Comment by kanej** [comment]
@zoeyTM the intention here is update `hardhat-ignition` so that the module parameters loading from cli and from file go through our custom JSON parsing logic:

https://github.com/NomicFoundation/hardhat-ignition/blob/d8889a5e5e3b6b1d277dfa8937395e161367e871/packages/hardhat-plugin/src/index.ts#L477

https://github.com/NomicFoundation/hardhat-ignition/blob/d8889a5e5e3b6b1d277dfa8937395e161367e871/packages/hardhat-plugin/src/index.ts#L486

The `JSON.parse` reviver function should:
1. Check for string values, if they meet the regex /d+n/ then convert the string to a `bigint`
2. If the value is a number check whether it is larger than `Number.MAX_SAFE_INTEGER` and throw an error indicating the number should be encoded as a string "\n"

Can you also put together the docs update to the module parameter section to add an explanation and example of an encoded bigint.
