### ISSUE TITLE
Unexpected next nonce error

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#676]
While testing the new `create2` functionality I hit a next nonce error. I am believe that the actual issue is that some of the transactions are reverting but somehow we are triggering the next nonce error before displaying the revert message:

![image](https://github.com/NomicFoundation/hardhat-ignition/assets/24030/34d85fa1-9b20-4d76-aa34-52822035fc25)

## Reproduction Steps

In the `create2` branch, build then `cd` to the `ENS` example, and run the deploy with the `create2` strategy:

```shell
cd ./examples/ens
npx hardhat ignition deploy ./ignition/modules/ENS.js --strategy create2
```

**Comment by zoeyTM** [comment]
I have confirmed a few things:

1. There is a race condition that happens when one transaction in a batch reverts that causes the nonce error above
2. The race condition is not specific to `create2` and does exist in the `basic` strategy as well
3. The reason the `ENS` module is failing is due to a permissions issue. Specifically, the owner of the ENS contract is set to `msg.sender` which, when deploying with `create2`, is the `CreateX` contract address.
