### ISSUE TITLE
Add an upper limit for the maxFeePerGas field

### ISSUE THREAD

**Issue by dsapaev** [NomicFoundation/hardhat-ignition#685]
We want to use Hardhat Ignition for our deployments but sometimes a network fee is too high and we don't want to spent so much money for it. 

1. Can you add new parameter to the hardhat.network object - feePerGasLimit? If calculated value of a maxFeePerGas is grater, than a feePerGasLimit then sending tx will fail. Something like this:

```
if (latestBlock.baseFeePerGas !== undefined) {
            // Logic copied from ethers v6
            const maxPriorityFeePerGas = 1000000000n; // 1gwei
            const maxFeePerGas = latestBlock.baseFeePerGas * 2n + maxPriorityFeePerGas;
            if(maxFeePerGas > hre.network.config.feePerGasLimit) throw new FeeOutOfBoundError(maxFeePerGas);
            return {
                maxFeePerGas,
                maxPriorityFeePerGas,
            };
        }
```
2. It will be great, if we can set maxPriorityFeePerGas at hardhat.config.js.

**Comment by kanej** [comment]
We are opting for creating the setting under `networks` in the Hardhat config:

```
networks: {
   mainnet: {
       ignition: {
           maxFeePerGas
       }
   }
}
```

The reasoning is that `maxFeePerGas` is a property of the relation between Ignition and a particular network. In a hierarchical structure, you could put it in either `networks > mainnet > ignition` or `ignition > networks > mainnet`. Since Ignition is a core part of HH, we will choose to add the config to the integral concept: `networks`.
