### ISSUE TITLE
Don't use `process.exit` in Hardhat tasks

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat-ignition#708]
I just noticed that our plugins are using `process.exit` in some tasks to exit with an error code (e.g. `process.exit(1)`). Instead of doing that, we should be using [`process.exitCode`](https://nodejs.org/api/process.html#processexitcode_1)

**Comment by mabsattar** [comment]
Hi, I'd like to tackle that, can you please assign me.

**Comment by kanej** [comment]
@alcuadrado can I double check here.

The reason not to use `process.exit(...)` is we want the standard tear down to happen within the Hardhat task rather than exiting immediately?

So the intention is, set the exit code to `1` indicating failed, and then return out of the task with no further work rather than `process.exit`. This gets us both a stop in the task processing and, after tear down, the exit code we want for the process?
