### ISSUE TITLE
Add maxPriorityFeePerGas param to config

### ISSUE THREAD

**Issue by dsapaev** [NomicFoundation/hardhat-ignition#728]
We utilize your tool for deployments, but encounter an issue when attempting to deploy our contracts to Polygon - there's a maxPriorityFeePerGas limit of 30 GWei on the mainnet. Below is a snippet of your code for configuring transaction fees (please refer to the EIP1193JsonRpcClient in the ignition-core):
```
// We prioritize EIP-1559 fees over legacy gasPrice fees
        if (latestBlock.baseFeePerGas !== undefined) {
            // Logic copied from ethers v6
            const maxPriorityFeePerGas = 1_000_000_000n; // 1gwei
            const maxFeePerGas = latestBlock.baseFeePerGas * 2n + maxPriorityFeePerGas;
            return {
                maxFeePerGas,
                maxPriorityFeePerGas,
            };
        }
```
Due to this limitation, we're unable to configure maxPriorityFeePerGas, resulting in all our transactions being stuck in the mempool and never executed. Is it possible to either add maxPriorityFeePerGas to the config file or calculate it using the fee from the previous block?"

**Comment by lukoyanov** [comment]
I second this. In Polygon (and some other networks), due to the relatively low price of the native token (MATIC), some users set deliberately high gas values (since it's not economically problematic) when sending transactions. Often, these aren't even EIP-1559 transactions, but legacy transactions (type 0).

With a hardcoded maxPriorityFeePerGas value of 1 Gwei inside HH Ignition, we have no mechanisms to combat such situations. The only solution is to sit and wait, restarting the deployment.

A mechanism for increasing the price could help here, but unfortunately, it's not customizable either.

**Comment by kanej** [comment]
We need to investigate more. We suspect that **Polygon** has a different logic than that captured in the `maxFeePerGas` equation shown above.
So we suspect that two moves are needed:

1. Support configuring `maxPriorityFeePerGas`
2. Add a specific override in our calculation logic for polygon.
